import "./globals.css";

export const metadata = {
  title: "Swaron.io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="bg-app_bg"
      >
        {children}
      </body>
    </html>
  );
}
